// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"WeaponSkill","status":true,"description":"Change skill id of attack for each weapon.","parameters":{}},
{"name":"KJ_Gobang","status":true,"description":"Gobang. v1.04","parameters":{"VariableId":"1","CancelText":"认输","RegretEnable":"true","Level":"6","Size":"750","Sound":"Break","UI":"UI"}}
];
